runtime: python
env: flex

runtime_config:
  python_version: 3.6

manual_scaling:
  instances: 1

entrypoint: gunicorn -b :$PORT -k eventlet main:app

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
