runtime: python
env: flex

runtime_config:
    python_version: 3.6

entrypoint: gunicorn -b :$PORT --worker-class eventlet main:app

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
  #script: main.app
